### ISSUE TITLE
epstata.py

### ISSUE THREAD

**Issue by qiaoqiaozhu** [sechilds/stataconf2015#1]
Hi, 

I come across your inspiring talk. Does epstata.py work with mac and network version of stata? On my mac I have STATA SE 13 and on my work windows machine a have a network connection to STATA MP. How should I modify the file to make that work?

Thanks, 
Qiaoqiao

**Comment by sechilds** [comment]
Thanks for the nice comment about the talk. It was fun to give at StataConf last year.

The line you need to change to get `estate.py` to work on the Mac (or Windows) is line 22:

```
self.proc = sp.Popen(['stata-mp'], stdin=sp.PIPE, stdout=sp.PIPE, bufsize=1)
                       ^^^^^^^^
```

The code that I'm pointing at with the "^" characters is where you need to put the command to run command line Stata. That command should be found in the _Getting Started with Stata_ manuals on the Stata website. The Mac one is: [http://www.stata.com/manuals14/gsm.pdf](http://www.stata.com/manuals14/gsm.pdf). See page 125-6.

Basically, the command will vary by the different versions of Stata. On the Mac, the Stata command line is within the Stata.app bundle (which is just a folder). So it might be in the path `/Applications/Stata/StataSE.app/Contents/MacOS`.

Your first step should be to be able to run Stata from the command line (the Terminal program in the Applications/Utilities folder). If you run it, you will get something that looks like this:

![stata-mp](https://cloud.githubusercontent.com/assets/119660/13203460/fa8fee6a-d875-11e5-83f6-fb1e4f157d79.png)

The command to run it will be something like:

```
/Applications/Stata/StataMP.app/Contents/MacOS/stata-mp
```

But for Stata SE, you will probably need to replace StataMP with StataSE.

Windows is a bit more tricky to get working. I'm still working on that one.

**Comment by qiaoqiaozhu** [comment]
Thanks for such detailed and prompt reply. It works with a caveat. I find out in El Captan, you need to have system integrity protection disabled (so being able to access urs/bin) for this to work. 
Great work.

**Comment by otteheng** [comment]
Hi,

I'm trying to get this working on windows. I think the line that you specified in a previous answer is where I'm having issues. Have you been able to resolve the issues related to implementation on Windows?

Thanks!

**Comment by acozzubo** [comment]
Thanks for the material! I am also stuck making it work for Windows10 with Stata16MP.

Do you have any suggestions? Thanks!
